import { useState } from 'react';
import { motion } from 'motion/react';
import { ArrowUpRight, CodeXml, Database, Palette, Layers3, UsersRound, Workflow, X, ChevronLeft, ChevronRight } from 'lucide-react';
import { areas, moments, teachers, timeline } from '../../data/siteData';
import ProjectsArchive from './ProjectsArchive';
const icons = [CodeXml, Workflow, Database, Layers3, Palette, UsersRound];
const reveal = { initial:{opacity:0,y:24}, whileInView:{opacity:1,y:0}, viewport:{once:true,amount:.15}, transition:{duration:.55} };
function Heading({ index, kicker, title, text }) { return <motion.div {...reveal} className="section-heading"><p className="eyebrow"><span />{index} — {kicker}</p><h2>{title}</h2>{text && <p>{text}</p>}</motion.div>; }
function Placeholder({label}) { return <div className="image-placeholder"><span>{label}</span><i /></div>; }
export default function TechSections() { const [lightbox,setLightbox]=useState(null); const move=d=>setLightbox((lightbox+d+moments.length)%moments.length); return <>
<section id="tecnica" className="section section-alt"><div className="content-grid about-grid"><Heading index="02" kicker="LA TÉCNICA" title={<>Una comunidad que aprende <em>haciendo.</em></>} text="Un espacio para descubrir, crear y desarrollar soluciones tecnológicas con propósito."/><motion.div {...reveal} className="about-panel"><p className="panel-number">// 01</p><h3>Formación en movimiento.</h3><p>La información específica sobre duración, niveles, convenios y resultados se mantiene editable hasta contar con datos institucionales confirmados.</p><div className="about-stats"><span>Habilidades<br/><b>por definir</b></span><span>Proyectos<br/><b>por registrar</b></span></div></motion.div></div></section>
<section className="section"><div className="section-container"><Heading index="03" kicker="QUÉ HACEMOS" title={<>Construimos bases para <em>crear.</em></>} text="Áreas de aprendizaje que se articulan en cada experiencia del programa."/><div className="area-grid">{areas.map(([n,title,text],i)=>{const Icon=icons[i];return <motion.article {...reveal} transition={{delay:i*.05}} className="area-card" key={n}><span>{n}</span><Icon size={25}/><h3>{title}</h3><p>{text}</p></motion.article>})}</div></div></section>
<ProjectsArchive/>
<section id="momentos" className="section"><div className="section-container"><Heading index="05" kicker="MOMENTOS" title={<>Momentos que construyen<br/>nuestra <em>historia.</em></>} text="Galería lista para fotografías institucionales autorizadas."/><div className="moment-grid">{moments.map((m,i)=><button className={'moment-card moment-'+i} key={m.title} onClick={()=>setLightbox(i)} aria-label={'Abrir '+m.title}>{m.image?<img src={m.image} alt={m.title} loading="lazy"/>:<Placeholder label={m.label}/>}<span>{m.title}<b>↗</b></span></button>)}</div></div></section>
<section id="docentes" className="section section-alt"><div className="section-container"><Heading index="06" kicker="DOCENTES" title={<>Quienes guían cada <em>línea de código.</em></>} text="Conoce al equipo docente de la técnica. Los perfiles se actualizan con información institucional autorizada."/><div className="teacher-grid">{teachers.map((teacher,i)=><motion.article {...reveal} transition={{delay:i*.1}} className="teacher-card" key={teacher.id}><div className="teacher-photo">{teacher.image?<img src={teacher.image} alt={teacher.name} loading="lazy"/>:<><span>{teacher.initials}</span><i/></>}<p>DOCENTE · {String(i+1).padStart(2,'0')}</p></div><div className="teacher-info"><span>{teacher.role}</span><h3>{teacher.name}</h3><p>{teacher.bio}</p><button disabled>Perfil disponible pronto <ArrowUpRight size={16}/></button></div></motion.article>)}</div></div></section>
<section id="estudiantes" className="section"><div className="section-container student-layout"><div><Heading index="07" kicker="ESTUDIANTES" title={<>El próximo perfil destacado puede estar <em>aquí.</em></>} text="Este espacio se activa cuando la institución defina la persona y comparta información autorizada."/><a className="text-link" href="#contacto">Proponer información verificada</a></div><div className="spotlight"><div className="spotlight-avatar">?</div><p>ESTUDIANTE DESTACADO</p><h3>Información pendiente</h3><span>Nombre · generación · logros · tecnologías</span></div></div></section>
<section className="section section-alt"><div className="section-container"><Heading index="08" kicker="HISTORIA" title={<>La ruta también se <em>programa.</em></>}/><div className="timeline">{timeline.map((item,i)=><motion.article {...reveal} transition={{delay:i*.1}} key={item.title}><span>{item.date}</span><div><i/><h3>{item.title}</h3><p>{item.text}</p></div></motion.article>)}</div></div></section>
<section id="contacto" className="contact-section"><p className="eyebrow"><span/>09 — CONTACTO</p><h2>Construyamos la<br/><em>siguiente versión.</em></h2><p>Incluye aquí los canales de contacto oficiales cuando sean confirmados.</p><a href="mailto:" className="button-primary">Contacto institucional <ArrowUpRight size={18}/></a></section>
{lightbox!==null&&<div className="lightbox" role="dialog" aria-modal="true" aria-label="Galería"><button aria-label="Cerrar" onClick={()=>setLightbox(null)}><X/></button><button aria-label="Anterior" onClick={()=>move(-1)}><ChevronLeft/></button><div>{moments[lightbox].image?<img src={moments[lightbox].image} alt={moments[lightbox].title}/>:<Placeholder label="FOTOGRAFÍA PENDIENTE"/>}<h3>{moments[lightbox].title}</h3></div><button aria-label="Siguiente" onClick={()=>move(1)}><ChevronRight/></button></div>}
</>; }
